# SPDX-FileCopyrightText: 2025 - 2026 Frederic Ruget <fred@atlant.is> (GitHub: @douzebis)
#
# SPDX-License-Identifier: MIT

version = 1
SPDX-PackageName = "yb"
SPDX-PackageSupplier = "Frederic Ruget <fred@atlant.is>"
SPDX-PackageDownloadLocation = "https://github.com/douzebis/yb"

[[annotations]]
path = ["rust/Cargo.lock", "rust/yb-core/tests/fixtures/**.yaml", "yb.1", ".gitignore", "LICENSE"]
precedence = "aggregate"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "vendor/vpicc-rs/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Nitrokey GmbH"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "vendor/piv-authenticator/**"
precedence = "aggregate"
SPDX-FileCopyrightText = ["Nicolas Stalder <n@stalder.io>", "Nitrokey GmbH"]
SPDX-License-Identifier = "Apache-2.0 OR MIT"
